source('R/ExploratoryDataAnalysis/LoadData.R')
png(filename='plot3.png', width=480, height=480, units='px')
lncol<-c('black','red','blue')
lbls<-c('Sub_metering_1','Sub_metering_2','Sub_metering_3')
plot(Data$Time,Data$Sub_metering_1,type='l',col=lncol[1],xlab='',ylab='Energy sub metering')
lines(Data$Time,Data$Sub_metering_2,col=lncol[2])
lines(Data$Time,Data$Sub_metering_3,col=lncol[3])
legend('topright',legend=lbls,col=lncol,lty='solid')
dev.off()